image:
  repository: ghcr.io/raydak-labs/configarr
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8787

persistence:
  configsPath: "/mnt/metadata/ix-applications/releases"
  dataPath: "/mnt/metadata/configarr"

env:
  TZ: Australia/Brisbane
  PUID: "568"
  PGID: "568"

